# This is the default configuration. A .glide.toml file in your home directory
# can override these settings.

[settings]

# Enable animations.
animate = true

# Disable each space by default. When this is set, Use the
# toggle_space_activated command to enable a space.
default_disable = true

# Focus the window under the mouse as it moves.
focus_follows_mouse = true

# Move the mouse to the middle of the window each time the focus changes.
mouse_follows_focus = true

# Hide the mouse each time a new window is focused. Ignored if
# mouse_follows_focus is false.
mouse_hides_on_focus = true

# Gap between windows and screen edges (in pixels).
outer_gap = 0

# Gap between adjacent windows (in pixels).
inner_gap = 0

# Visual bars for window groups (tabbed/stacked containers).
group_bars.enable = true
group_bars.thickness = 6
group_bars.horizontal_placement = "top"
group_bars.vertical_placement = "right"

[settings.experimental]

# Enables the experimental status icon, which shows the current space.
status_icon.enable = true

[keys]
# Modifier and key names must be capitalized.

# Toggle whether the current space is managed by Glide.
"Alt + Z" = "toggle_space_activated"

# Focus the window in the specified direction.
"Alt + H" = { move_focus = "left" }
"Alt + J" = { move_focus = "down" }
"Alt + K" = { move_focus = "up" }
"Alt + L" = { move_focus = "right" }

# Move the focused window in the specified direction.
"Alt + Shift + H" = { move_node = "left" }
"Alt + Shift + J" = { move_node = "down" }
"Alt + Shift + K" = { move_node = "up" }
"Alt + Shift + L" = { move_node = "right" }

# Move up or down the tree hieararchy, selecting a parent or child node
# respectively.
"Alt + A" = "ascend"
"Alt + D" = "descend"

# Toggle between saved layouts on the active space. This allows you to access
# layouts from other screen sizes.
"Alt + N" = "next_layout"
"Alt + P" = "prev_layout"

# Create a container above the current node in the specified orientation.
# This has the effect of "splitting" the current window/node once a new node
# is added.
"Alt + Backslash" = { split = "horizontal" }
"Alt + Equal" = { split = "vertical" }

# Change the parent node to a horizontal or vertical group, also known as
# "tabbed" and "stacked" respectively.
"Alt + T" = { group = "horizontal" }
"Alt + S" = { group = "vertical" }
"Alt + E" = "ungroup"

# Float the current node. Floating windows are allowed to overlap and keep
# whatever size and position you give them. Note that they do not actually
# float on top of other windows, as that would require disabling security
# protection on your machine.
"Alt + Shift + Space" = "toggle_window_floating"

# Toggle between focusing floating nodes. When switching to floating mode
# this will put all floating windows on top, and when switching away it will
# hide floating windows.
"Alt + Space" = "toggle_focus_floating"

# Toggle whether the focused node takes up the whole screen.
"Alt + F" = "toggle_fullscreen"

#
# Utilities
#

# Execute an arbitrary command. Accepts an array or space-delimited string as args.
# DISABLED by default; see exec_cmd in Cargo.toml.
# "<key>" = { "exec" = ["bash", "-c", "echo 'hello world' >/tmp/test.txt"] }

#
# Developer commands
#

# Save the current state to the restore file and exit.
# Restore this with the --restore option when starting glide.
# Note that the restore file is only useful when upgrading or restarting
# glide itself; it is not valid after the user logs out or restarts.
"Alt + Shift + E" = "save_and_exit"

# Print the current layout in the logs.
"Alt + Shift + D" = "debug"

"Alt + M" = "show_timing"
"Alt + Shift + S" = "serialize"
